### ISSUE TITLE
item 里面元素大小问题

### ISSUE THREAD

**Issue by howyhuang** [lipten/slidePage#11]
请教下大神，你是怎么解决移动端全屏div.item下子元素的，宽高和布局问题呢？
比如设计稿750*1334，我怎么设置子元素的大小
我现在用sass计算样式成rem，js来设置html对应的dip和字体大小，但是全屏活动在ip4小屏幕手机还是不能完美展现，请教大神有什么方法望告知，还是说百分比来解决或者根据设备整个页面缩放处理···哎 头疼

**Comment by lipten** [comment]
建议试试淘宝的flexiable方案，http://www.tuicool.com/articles/nmm6reE
常规固定尺寸用rem ，一些需要适应屏幕宽度的就要用百分比。
