### ISSUE TITLE
demo page can't work

### ISSUE THREAD

**Issue by scyankai** [lipten/slidePage#15]
Mixed Content: The page at 'https://lipten.link/projects/slidePage/demo.html' was loaded over HTTPS, but requested an insecure script 'http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

browser ：desktop chrome

**Comment by lipten** [comment]
我暂时移除了ssl，现在可以直接访问http://lipten.link/projects/slidePage/demo.html
