### ISSUE TITLE
js添加slidepage无效，仅显示最后一张图片

### ISSUE THREAD

**Issue by zhmiblog** [lipten/slidePage#19]
<script type="text/javascript" src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>	
	<script type="text/javascript" src="./source/slidePage/slidePage.min.js"></script>	
	
	<script>
		var ctg = localStorage.ctg;
		var max = localStorage.max;
		var fa = document.getElementById("page1"); 
        $.getJSON("https://2018happy.club/ct.json", function (data){
		var ctd=data[ctg];
		for(var i=0;i<ctd.length;i++){
		   for(var j=1;j<parseInt(max)+1;j++){
				var ta = fa.cloneNode(true); 
				ta.setAttribute("id", ctd[i] + j);
				ta.className ="slide-page page1 transition";
				ta.getElementsByTagName("img")[0].src="./pic/"+ctg+"/"+ctd[i]+j+".jpg";
				ta.getElementsByTagName("h2")[0].innerHTML=ctd[i]+j;
				fa.parentNode.appendChild(ta);
           }
		}
		})
		var slide = new slidePage({page: 1,});
 	</script>

**Comment by lipten** [comment]
<script>
	var ctg = localStorage.ctg;
	var max = localStorage.max;
	var fa = document.getElementById("page1"); 
    $.getJSON("https://2018happy.club/ct.json", function (data){
	var ctd=data[ctg];
	for(var i=0;i<ctd.length;i++){
	   for(var j=1;j<parseInt(max)+1;j++){
			var ta = fa.cloneNode(true); 
			ta.setAttribute("id", ctd[i] + j);
			ta.className ="slide-page page1 transition";
			ta.getElementsByTagName("img")[0].src="./pic/"+ctg+"/"+ctd[i]+j+".jpg";
			ta.getElementsByTagName("h2")[0].innerHTML=ctd[i]+j;
			fa.parentNode.appendChild(ta);
                 }
	  }
         var slide = new slidePage({page: 1,});
	})
	
</script>

**Comment by lipten** [comment]
getJSON是异步操作，需要在回调里添加完dom之后更新重绘一下
```
<script>
        var slide = new slidePage({page: 1,});
	var ctg = localStorage.ctg;
	var max = localStorage.max;
	var fa = document.getElementById("page1"); 
    $.getJSON("https://2018happy.club/ct.json", function (data){
	var ctd=data[ctg];
	for(var i=0;i<ctd.length;i++){
	   for(var j=1;j<parseInt(max)+1;j++){
			var ta = fa.cloneNode(true); 
			ta.setAttribute("id", ctd[i] + j);
			ta.className ="slide-page page1 transition";
			ta.getElementsByTagName("img")[0].src="./pic/"+ctg+"/"+ctd[i]+j+".jpg";
			ta.getElementsByTagName("h2")[0].innerHTML=ctd[i]+j;
			fa.parentNode.appendChild(ta);
            }
	}
        slide.update()
	})     
	
</script>
```
