### ISSUE TITLE
初始化不了slidePage

### ISSUE THREAD

**Issue by gerald-luo** [lipten/slidePage#24]
var slide = new slidePage();在这一段代码里报错，显示Uncaught TypeError: slidePage is not a constructor

**Comment by lipten** [comment]
检查一下有没有引入slidePage
可以以cdn的方式引入：
```
<script src="https://cdn.jsdelivr.net/gh/lipten/slidePage/dist/slidePage.min.js"></script>
```

**Comment by gerald-luo** [comment]
有引入slidePage的，换成以cdn的方式引入也还是报那个错误

**Comment by lipten** [comment]
在new slidePage(); 之前引入的吗？

**Comment by gerald-luo** [comment]
跟jquery有关系吗？是jquery报的这个错

**Comment by gerald-luo** [comment]
我把引入文件放到body闭合后面的话，没有报那个错了，报了另一个错：Uncaught TypeError: Cannot read property 'offsetHeight' of undefined，出现在
var methods = {
		slideScroll: function (index) {
			var itemheight = this.items[index].children[0].offsetHeight; 在这里

**Comment by lipten** [comment]
你的html结构是怎样的？

**Comment by gerald-luo** [comment]
这个报错也解决了，原来要每个page（<div class="slide-page"></div>）里下一层要有<div class="container"></div>，所以是必须这个结构才行吗？
<div class="slide-page part">
	<div class="container">
	页面内容
	</div>
</div>

**Comment by gerald-luo** [comment]
那个报错也解决了，每个页面结构是需要这样才行吗？<div class="slide-page part"><div class="container">页面内容</div></div>

**Comment by gerald-luo** [comment]
那个报错也解决了，每个页面是需要这样的结构才行是吗？
`<div class="slide-page part">
	<div class="container">
	页面内容
	</div>
</div>`

**Comment by gerald-luo** [comment]
那个报错也解决了，每个页面结构都必须在div.slide-page里下一层是div.container，页面内容就写在div.container是吗？

**Comment by lipten** [comment]
是的，div.slide-page下要有个容器元素包含所有页面内的元素的，因为要计算页面内容的高度
