### ISSUE TITLE
iOS里微信回弹效果导致页面切换不了的解决办法

### ISSUE THREAD

**Issue by gerald-luo** [lipten/slidePage#26]
在iOS里的网页在上拉到底部或下拉到顶部时，继续拉动会出现回弹效果，然后页面切换就不行了，这个要怎么解决呢？

**Comment by lipten** [comment]
你说的是不是在那种超出屏幕内容的滚动的情况下快速拉动产生的回弹效果，然后页面就不能切换了？

**Comment by gerald-luo** [comment]
对的，只要一出现那种回弹效果，滑动切换页面就不行了，一滑就会又出现回弹效果

**Comment by gerald-luo** [comment]
在iOS上出现的概率还比较大

**Comment by lipten** [comment]
好的，我修一下

**Comment by gerald-luo** [comment]
好的，谢谢

**Comment by gerald-luo** [comment]
我发现当我在页面里某一个控件添加touchstart、touchmove事件时，在触摸那个控件移动时，会比较容易触发导致回弹效果

**Comment by lipten** [comment]
页面里的控件要用touch事件最好阻止冒泡，stopPropagation

**Comment by gerald-luo** [comment]
嗯，好的，还有一个问题是iOS里微信当超出屏幕内容的滚动的情况下拉到尽头不放手一直拉页面内容会不断移动，这时松手会切换页面，切换页面后立即滑动切换页面时，也会有比较大几率会出现那种回弹效果

**Comment by gerald-luo** [comment]
提供一个想法，出现刚才那种不松手不断拉页面（这时scrollTop会不断增大或减小）的情况时，我在页面切换过程前before方法里让页面的scrollTop回到正常的数值并且让overflow-x：hidden，等到after方法里再让overflow-x：auto，然后暂时没出现那种页面回弹切换不了的情况了

**Comment by lipten** [comment]
@gerald-luo 修复好了，运行npm install slidePage 更新版本到3.2.1试试看

**Comment by gerald-luo** [comment]
不行啊，感觉体验更糟糕了，会出现触摸滑动到下一页时切换不了，还是停留到当前页，但是可以触摸滑动到上一页
