### ISSUE TITLE
在chrome中运行demo，使用鼠标滚轮和拖拽的方式均不能翻页

### ISSUE THREAD

**Issue by eimsteim** [lipten/slidePage#4]
RT，Chrome版本号：版本 47.0.2526.111 m
控制台未见加载脚本失败，是否是我运行demo的方式不正确呢？

**Comment by lipten** [comment]
目前只支持touch事件，请打开手机模拟器或直接用手机访问，正在准备出兼容PC的版本，不便之处敬请谅解

**Comment by lipten** [comment]
0.5版本以上已支持桌面端鼠标滚轮和键盘上下键滚动了。
