### ISSUE TITLE
mac 触屏的滚动有点问题

### ISSUE THREAD

**Issue by zlxbuzz** [lipten/slidePage#8]
滑动稍微大点就会滑动多页

**Comment by lipten** [comment]
这个目前还没找到办法解决，触控板滚动稍大有个惯性滚动，惯性滚动依然会触发浏览器的滚动事件，而且浏览器没有提供触控板设备还是鼠标设备的接口，没法判断。

**Comment by RanQiwu** [comment]
测试那边今天也反馈了这个问题，不知道现在有解决思路没？

**Comment by acgotakuatdji** [comment]
@lipten https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1243

fullpage.js有个根据滑动加速度来回避滑动多页的处理 是否可以参考一下？

**Comment by RanQiwu** [comment]
![image](https://user-images.githubusercontent.com/22112008/42148630-989e9660-7e05-11e8-8133-7710b3acc8ce.png)
奶奶的，还是得使用大厂商的，要不然改了一个又一个。bug完全改不完。

**Comment by RanQiwu** [comment]
https://github.com/alvarotrigo/fullPage.js/tree/master/lang/chinese#fullpagejs   你值得拥有。

**Comment by lipten** [comment]
@zlxbuzz @RanQiwu @acgotakuatdji 学习了fullpage的方案，增加滚轮间隔判断，避免了触控板多次滑动的问题。

**Comment by acgotakuatdji** [comment]
在线的demo也同样更新了么？ @lipten

**Comment by lipten** [comment]
@acgotakuatdji 刚更新了，谢谢提醒

**Comment by acgotakuatdji** [comment]
@lipten  http://lipten.link/projects/slidePage3/examples/fullFeatured.html 

这个页面Mac触摸板滑动 还是一次滑两页啊。。。

**Comment by lipten** [comment]
@acgotakuatdji 可能是你的浏览器缓存了，换个试试
